services:
    redis:
        container_name: webcache-redis
        image: docker.io/redis:alpine3.15
        restart: always
        volumes:
            - ./redis:/usr/local/etc/redis:ro
        security_opt:
            label: disable
        command: "redis-server /usr/local/etc/redis/redis.conf"

    webcache:
        container_name: webcache-server
        image: localhost/alvidir/webcache:1.0.0
        restart: always
        ports:
            - 8000:8000
        volumes:
            - .config:/etc/webcache/config.yaml:ro
        security_opt:
            label: disable
        depends_on:
            - redis
        env_file:
            - .env