version: '3.8'

services:
    redis:
        container_name: redis
        image: docker.io/redis:latest
        restart: always
        ports:
            - "6379:6379"
        networks: 
            - cache

    # webcache:
    #     container_name: webcache-server
    #     image: localhost/alvidir/webcache:0.1.0
    #     restart: always
    #     networks: 
    #         - cache
    #     env_file:
    #         - .env

networks:
    # Cache network works as a bridge between webcache and the redis server
    cache:
        name: cache
        driver: bridge