FROM docker.io/golang:1.18 as builder

RUN apt update

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o webcache cmd/webcache/main.go

######## Start a new stage from scratch #######
FROM docker.io/alpine:3.15.5  

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/webcache .

# Command to run the executable
CMD [ "./webcache" ]
