FROM envoyproxy/envoy:v1.14-latest

LABEL maintainer="Hector Morales <hector.morales.carnice@gmail.com>"
LABEL repo-url="https://github.com/alvidir/unsplash-api"
LABEL version="alpha"

RUN apt-get update && \ 
    apt-get install -y curl

COPY envoy/envoy.yaml /etc/envoy
CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml"]