FROM docker.io/nginx:stable-alpine

LABEL maintainer="Hector Morales <hector.morales.carnice@gmail.com>"
LABEL repo-url="https://github.com/alvidir/webcache"
LABEL version="alpha"

COPY nginx/nginx.conf /etc/nginx