FROM golang:latest as builder

RUN apt update

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

# RUN go test ./...
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o tp-auth cmd/webcache/main.go

######## Start a new stage from scratch #######
FROM alpine:latest  

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/webcache .

# Command to run the executable
CMD [ "./webcache" ]
